# Generated by Django 4.1.7 on 2023-04-17 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembroxprojecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fecha_inicio', models.CharField(max_length=256)),
                ('fecha_fin', models.CharField(max_length=256)),
                ('mision', models.CharField(max_length=256)),
                ('vision', models.CharField(max_length=256)),
                ('objetivo', models.CharField(max_length=256)),
                ('espectativa', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=256)),
                ('miembroxprojecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembroxprojecto.miembroxprojecto')),
            ],
        ),
    ]
