# Generated by Django 4.1.7 on 2023-04-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realiza', '0001_initial'),
        ('reacciones', '0001_initial'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('contenido', models.CharField(max_length=256)),
                ('comentarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comentarios.comentarios')),
                ('reacciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reacciones.reacciones')),
                ('realiza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realiza.realiza')),
            ],
        ),
    ]
