# Generated by Django 4.1.7 on 2023-04-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.CharField(max_length=256)),
                ('fecha_fin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CentroCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('direccion', models.CharField(max_length=256)),
                ('junta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro_cultural.junta')),
            ],
        ),
    ]
