# Generated by Django 4.1.7 on 2023-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contactanos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=254)),
                ("nombre", models.CharField(max_length=256)),
                ("telefono", models.IntegerField(blank=True, max_length=9)),
                ("mensajes", models.CharField(max_length=256)),
            ],
        ),
    ]
