# Generated by Django 4.1.7 on 2023-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactanos", "0002_alter_contactanos_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactanos",
            name="nombre",
            field=models.CharField(max_length=256),
        ),
    ]
