# Generated by Django 4.1.7 on 2023-04-17 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conformado', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('mision', models.CharField(max_length=256)),
                ('vision', models.CharField(max_length=256)),
                ('conformado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conformado.conformado')),
                ('proyectos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyectos')),
            ],
        ),
    ]
