# Generated by Django 4.1.7 on 2023-03-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=256)),
                ("apellido", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256)),
            ],
        ),
    ]
