# Generated by Django 4.1.7 on 2023-03-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domicilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=256)),
                ("no_calle", models.IntegerField()),
                ("pais", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name="users",
            name="domicilio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuarios.domicilio",
            ),
        ),
    ]
