# Generated by Django 4.1.7 on 2023-04-17 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('junta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.area'),
        ),
        migrations.AlterField(
            model_name='junta',
            name='fecha_fin',
            field=models.CharField(max_length=256),
        ),
    ]
