# Generated by Django 4.1.7 on 2023-04-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=256)),
                ('fecha_inicio', models.CharField(max_length=256)),
                ('fecha_fin', models.CharField(max_length=256)),
            ],
        ),
    ]
